### ISSUE TITLE
STC89C compatibility?

### ISSUE THREAD

**Issue by MidnightWonderer** [nekromant/stcdude#5]
Hello,
I can get stcdude working for 12C series but 89C.
I know that 89C series are older one and might use different protocol but I cant be sure.
My breadboard is somewhat unreliable.
My box is Linux I cannot use ISP dowloader that STC provided.

So I want to ask weather stcdude support 89C series or not?

**Comment by nekromant** [comment]
AFAIK they 89C use a totally different protocol. Unfortunately, I don't have any 89C hardware to test myself or sniff and implrment, sorry.

**Comment by MidnightWonderer** [comment]
How unfortunate, I happened to have 3 of them at my home.
How about I order 10 of 89C52RC for you for free as a contribution to this project?
To accept the offer I just need your name and shipping address.

My email is midnight underscore w at gmx dot com.

**Comment by MidnightWonderer** [comment]
@nekromant It look like https://github.com/van9ogh/stc-isp support 89C series.  
Nevertheless, The offer is still valid until the end of this month.  
You can send required info to my email and comment here for authenticity.  
You can also decline the offer right away.

**Comment by nekromant** [comment]
Sorry for the delay. I gave stc-isp a quick look. So far looks like a very similar (or same) protocol. If you really want, you can drop me an email and I'll give STC89C a look. But note - since I live in Russia it may take a month  or even two for your parcel to arrive. We have a _very_ slow post service (

**Comment by MidnightWonderer** [comment]
stc-isp also print some kind of debug log when flashing.
Here the output.
```
0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

0000: 7F 

Start Programming>>>
target is 1/2 gain 
target is double speed(6T) 
target's P1.1&P1.0 normal 

<<<<< Received target_info:
0000: 68 00 3B 00 03 BE 03 C2 03 C2 03 BE 03 C2 03 BE 
0010: 03 C2 03 C2 43 43 EC F0 02 82 00 00 00 00 00 00 
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0030: 00 00 00 00 00 00 00 00 00 A5 16 

target_hz is 16000000

Baudrate is 9600

>>>>> Send MSG:
0000: 46 B9 6A 00 0C 8F FF CC 00 68 28 81 E1 16 

Baudrate is 9600

<<<<< Receive MSG:
0000: 46 B9 68 00 0C 8F FF CC 00 68 28 81 DF 16 

Baudrate is 9600

>>>>> Send MSG:
0000: 46 B9 6A 00 0B 8E FF CC 00 68 17 4D 16 

Baudrate is 9600

<<<<< Receive MSG:
0000: 46 B9 68 00 0B 8E FF CC 00 68 17 4B 16 

>>>>> Send MSG:
0000: 46 B9 6A 00 06 80 F0 16 

<<<<< Receive MSG:
0000: 46 B9 68 00 06 80 EE 16 

>>>>> Send MSG:
0000: 46 B9 6A 00 06 80 F0 16 

<<<<< Receive MSG:
0000: 46 B9 68 00 06 80 EE 16 

>>>>> Send MSG:
0000: 46 B9 6A 00 06 80 F0 16 

<<<<< Receive MSG:
0000: 46 B9 68 00 06 80 EE 16 

>>>>> Send MSG:
0000: 46 B9 6A 00 06 80 F0 16 

<<<<< Receive MSG:
0000: 46 B9 68 00 06 80 EE 16 

>>>>> Send MSG:
0000: 46 B9 6A 00 06 80 F0 16 

<<<<< Receive MSG:
0000: 46 B9 68 00 06 80 EE 16 

>>>>> Send MSG:
0000: 46 B9 6A 00 07 84 02 F7 16 

<<<<< Receive MSG:
0000: 46 B9 68 00 06 80 EE 16 

>>>> Send MSG:
0000: 46 B9 6A 00 8C 00 00 00 00 00 00 80 02 00 06 02 
0010: 00 62 75 81 08 12 00 66 E5 82 60 03 02 00 03 79 
0020: 00 E9 44 00 60 1B 7A 00 90 00 6A 78 01 75 A0 00 
0030: E4 93 F2 A3 08 B8 00 02 05 A0 D9 F4 DA F2 75 A0 
0040: FF E4 78 FF F6 D8 FD 78 00 E8 44 00 60 0A 79 01 
0050: 75 A0 00 E4 F3 09 D8 FC 78 00 E8 44 00 60 0C 79 
0060: 00 90 00 01 E4 F0 A3 D8 FC D9 FA 02 00 03 75 08 
0070: 00 22 75 82 00 22 00 00 00 00 00 00 00 00 00 00 
0080: 00 00 00 00 00 00 00 00 00 00 00 00 D6 16 

<<<<< Receive MSG:
0000: 46 B9 68 00 07 80 60 4F 16 

>>>>> Send MSG:
0000: 46 B9 6A 00 06 82 F2 16 

close uart

Program OK
Have already encrypt.
```

Email was sent to the email with ncrmnt domain.

**Comment by MidnightWonderer** [comment]
I just want to let you know that up until now I don't receive any email reply.

**Comment by nekromant** [comment]
I didn't get any emails, not even in 'spam' folder. Maybe you've misspelled it? 
andrew {at} ncrmnt {dot} org

**Comment by MidnightWonderer** [comment]
Email resend. Sorry for the delay.

**Comment by MidnightWonderer** [comment]
How is it?
Are you able to program it with the current version?

**Comment by nekromant** [comment]
I've got the dev board ready and sniffed some packets, but didn't have a chance to finish the work on it just yet. Some places are still a mystery.

**Comment by nekromant** [comment]
@MidnightWonderer FIY: I've added the -n option to the current master for STC89, things got a little better but it's still mostly WiP and works once in a long while.

**Comment by grigorig** [comment]
Shameless plug, but stcgal had full STC89 support for almost two years by now.

**Comment by nekromant** [comment]
@grigorig Woah, you've done a great job there with stcgal! I started refactoring stcdude back in spring, but got buried under tons of stuff to do.

**Comment by grigorig** [comment]
Thanks. I guess I really made it my mission to get those MCUs supported...

**Comment by nekromant** [comment]
@grigorig I'm burying stcdude and putting a link to your tool (I should have done that a long time ago but I literary forgot that with all that rush with my PhD thesis!). It looks like my auto-generated mcudb has a few entries you're missing in stcgal, so you may want to check it out and use it.  

Since @MidnightWonderer donated me some STC89 mcus - I can mail them to you, if you drop me an email with your snail-mail address.
